-- Supabase schema for the Baccalaureate Library
-- Run this file once in Supabase SQL Editor.

create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  role text not null default 'student' check (role in ('student','admin')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.books (
  id bigint primary key,
  title text not null,
  icon text not null default '📚',
  cat text not null,
  description text not null default '',
  url text not null,
  date bigint not null default 0,
  popular integer not null default 0,
  is_new boolean not null default false,
  series text,
  is_folder boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.favorites (
  user_id uuid not null references auth.users(id) on delete cascade,
  book_id bigint not null references public.books(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (user_id, book_id)
);

create table if not exists public.activity_events (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  book_id bigint references public.books(id) on delete set null,
  event_type text not null check (event_type in ('open','download','favorite_add','favorite_remove')),
  created_at timestamptz not null default now(),
  meta jsonb not null default '{}'::jsonb
);

create table if not exists public.notifications (
  id bigint primary key generated by default as identity,
  book_id bigint references public.books(id) on delete cascade,
  title text not null,
  description text not null default '',
  category text not null default 'محتوى جديد',
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

-- Compatibility: make the schema safe to re-run on a project where tables already exist.
alter table public.profiles add column if not exists full_name text;
alter table public.profiles add column if not exists role text not null default 'student';
alter table public.profiles add column if not exists created_at timestamptz not null default now();
alter table public.profiles add column if not exists updated_at timestamptz not null default now();

alter table public.books add column if not exists icon text not null default '📚';
alter table public.books add column if not exists cat text not null default 'غير مصنف';
alter table public.books add column if not exists description text not null default '';
alter table public.books add column if not exists url text not null default '';
alter table public.books add column if not exists date bigint not null default 0;
alter table public.books add column if not exists popular integer not null default 0;
alter table public.books add column if not exists is_new boolean not null default false;
alter table public.books add column if not exists series text;
alter table public.books add column if not exists is_folder boolean not null default false;
alter table public.books add column if not exists created_at timestamptz not null default now();
alter table public.books add column if not exists updated_at timestamptz not null default now();

alter table public.favorites add column if not exists created_at timestamptz not null default now();
alter table public.activity_events add column if not exists meta jsonb not null default '{}'::jsonb;
alter table public.notifications add column if not exists category text not null default 'محتوى جديد';
alter table public.notifications add column if not exists is_active boolean not null default true;

-- Keep timestamps current when an existing row is edited.
create or replace function public.set_updated_at()
returns trigger
language plpgsql
security invoker
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_profiles_updated_at on public.profiles;
create trigger trg_profiles_updated_at before update on public.profiles for each row execute function public.set_updated_at();
drop trigger if exists trg_books_updated_at on public.books;
create trigger trg_books_updated_at before update on public.books for each row execute function public.set_updated_at();

create index if not exists idx_books_cat on public.books(cat);
create index if not exists idx_books_date on public.books(date desc);
create index if not exists idx_activity_user_created on public.activity_events(user_id, created_at desc);

-- Auto-create a profile row for every new Supabase Auth user.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, full_name) values (new.id, coalesce(new.raw_user_meta_data->>'full_name',''));
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

-- Admin helper: reads the role from profiles.
create or replace function public.is_admin()
returns boolean
language sql
stable
security definer set search_path = ''
as $$
  select exists(select 1 from public.profiles where id = auth.uid() and role = 'admin');
$$;

alter table public.profiles enable row level security;
alter table public.books enable row level security;
alter table public.favorites enable row level security;
alter table public.activity_events enable row level security;
alter table public.notifications enable row level security;

drop policy if exists profiles_select_own on public.profiles;
create policy profiles_select_own on public.profiles for select using (auth.uid() = id or public.is_admin());

drop policy if exists profiles_update_own on public.profiles;
create policy profiles_update_own on public.profiles for update using (auth.uid() = id or public.is_admin()) with check (auth.uid() = id or public.is_admin());

drop policy if exists books_public_read on public.books;
create policy books_public_read on public.books for select using (true);

drop policy if exists books_admin_write on public.books;
create policy books_admin_write on public.books for all using (public.is_admin()) with check (public.is_admin());

drop policy if exists notifications_public_read on public.notifications;
create policy notifications_public_read on public.notifications for select using (is_active = true);

drop policy if exists notifications_admin_write on public.notifications;
create policy notifications_admin_write on public.notifications for all using (public.is_admin()) with check (public.is_admin());

drop policy if exists favorites_own_select on public.favorites;
create policy favorites_own_select on public.favorites for select using (auth.uid() = user_id);
drop policy if exists favorites_own_insert on public.favorites;
create policy favorites_own_insert on public.favorites for insert with check (auth.uid() = user_id);
drop policy if exists favorites_own_update on public.favorites;
create policy favorites_own_update on public.favorites for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
drop policy if exists favorites_own_delete on public.favorites;
create policy favorites_own_delete on public.favorites for delete using (auth.uid() = user_id);

drop policy if exists activity_own_select on public.activity_events;
create policy activity_own_select on public.activity_events for select using (auth.uid() = user_id);
drop policy if exists activity_own_insert on public.activity_events;
create policy activity_own_insert on public.activity_events for insert with check (auth.uid() = user_id);

-- Explicit API grants. RLS policies still control which rows can be accessed.
grant usage on schema public to anon, authenticated;
grant select on public.books to anon, authenticated;
grant select on public.notifications to anon, authenticated;
grant select, update on public.profiles to authenticated;
grant select, insert, update, delete on public.favorites to authenticated;
grant select, insert on public.activity_events to authenticated;
grant select, insert, update, delete on public.books to authenticated;
grant select, insert, update, delete on public.notifications to authenticated;

-- Seed / synchronize the current library books.
insert into public.books (id,title,icon,cat,description,url,date,popular,is_new,series,is_folder) values
(1,'كتاب التاريخ','📚','تاريخ','الكتاب الدراسي لمادة التاريخ للصف الثاني الثانوي (PDF).','https://drive.google.com/file/d/1JQlVNklrEfleYtSSgntUNfUrP09mWhEu/view?usp=drive_link',20260305,75,FALSE,NULL,FALSE),
(2,'كتاب النحو','📖','لغة عربية','الكتاب الدراسي لمادة النحو للصف الثاني الثانوي (PDF).','https://drive.google.com/file/d/1DH8DeZDQqVnYfTovoug5EuGxTpA-7CqR/view?usp=sharing',20260305,75,FALSE,NULL,FALSE),
(3,'تأسيس رياضيات','📐','رياضيات','مذكرة تأسيس في الرياضيات للصف الثاني الثانوي (PDF).','https://drive.google.com/file/d/1qxqcD6p7RBt19L6EvxMRLa1aore8DmeD/view?usp=sharing',20260305,75,FALSE,NULL,FALSE),
(4,'الميسر في أصول الفقه الإسلامي','📘','مواد شرعية','كتاب الميسر في أصول الفقه الإسلامي – إعداد: عمر أحمد (PDF).','https://drive.google.com/file/d/1S3guUKhyG89zaRtfRr4HTE_GKc0-gh2Z/view?usp=sharing',20260305,75,FALSE,NULL,FALSE),
(5,'ملخص الدرس الأول - التاريخ (بناء الدولة المصرية)','🏛️','تاريخ','ملخص الدرس الأول في مادة التاريخ: بناء الدولة المصرية للصف الثاني الثانوي (PDF).','https://drive.google.com/file/d/1qeeYaaEYTOUMXc5DIwZHNEtXMNlhvh-l/view?usp=sharing',20260305,75,FALSE,NULL,FALSE),
(6,'الثلاثة الذين خُلِّفوا','📘','مواد شرعية','كتاب الثلاثة الذين خُلِّفوا – إعداد: عمر أحمد المنشاوي (PDF).','https://drive.google.com/file/d/1VH8UeFmU4hVWWrQCii4tYwscaspOfvX3/view?usp=sharing',20260305,75,FALSE,NULL,FALSE),
(7,'كورس تأسيس رياضة','🎥','رياضيات','كورس تأسيس الرياضيات للصف الثاني الثانوي.','https://drive.google.com/file/d/1eZAa1apbXTuTGpokc2oF5MZVLzxrvvi5/view?usp=sharing',20260712,100,FALSE,NULL,FALSE),
(8,'الفيزياء','⚛️','فيزياء','كتاب الفيزياء للصف الثاني الثانوي (PDF).','https://drive.google.com/file/d/11TRHopBJ1tfw4D26ScOpLGH4ff-Lt0US/view?usp=sharing',20260712,100,FALSE,NULL,FALSE),
(9,'الجزء الأول من الكورس التأسيسي للبرمجة','💻','برمجة','الجزء الأول من الكورس التأسيسي للبرمجة – إعداد وتجهيز: محمد رمضان الحرباوي.','https://drive.google.com/file/d/1VV4ooxWD_yGBb1atk14ndQ1RmDPPvbgv/view?usp=sharing',20260713,100,FALSE,NULL,FALSE),
(10,'الكافي في علوم البلاغة العربية','📖','لغة عربية','كتاب الكافي في علوم البلاغة العربية (HTML).','./الكافي_في_علوم_البلاغة_العربية.html',20260714,100,FALSE,NULL,FALSE),
(11,'كورس اللغة العربية','📖','كورسات','كورس اللغة العربية.','https://mhmdrmdan.yobader.com/course/kors-lghh-aarbyh',20260714,100,FALSE,NULL,FALSE),
(12,'كورس اللغة الإنجليزية','🇬🇧','كورسات','كورس اللغة الإنجليزية.','https://mhmdrmdan.yobader.com/course/lghh-anglyzyh',20260714,100,FALSE,NULL,FALSE),
(13,'كورس الفيزياء','⚛️','كورسات','كورس الفيزياء.','https://mhmdrmdan.yobader.com/course/fyzyaaa',20260714,100,FALSE,NULL,FALSE),
(14,'كورس التاريخ الوطني','🏛️','كورسات','كورس التاريخ الوطني.','https://mhmdrmdan.yobader.com/course/tarykh-otny',20260714,100,FALSE,NULL,FALSE),
(15,'كورس البرمجة والذكاء الاصطناعي','💻','كورسات','الكورس التأسيسي للبرمجة والذكاء الاصطناعي.','https://mhmdrmdan.yobader.com/course/kors-tasysy-brmgh',20260714,100,FALSE,NULL,FALSE),
(16,'أخبار وزارة التربية والتعليم','📰','كورسات','آخر الأخبار والحوارات والمعلومات الرسمية.','https://mhmdrmdan.yobader.com/course/ay-akhbar-bkhsos-ozarh-altrbyh-oaltaalym-ontham-albkalorya',20260714,100,FALSE,NULL,FALSE),
(17,'امتحان تاريخ - الدرس الأول','📝','امتحانات','امتحان على الدرس الأول في مادة التاريخ.','./index (1).html',20260713,100,FALSE,NULL,FALSE),
(18,'امتحان النحو','📝','امتحانات','امتحان تفاعلي على النحو.','./exam_naho.html',20260715,100,FALSE,NULL,FALSE),
(19,'أجمل مذكرة بلاغة للثانوية العامة بصفوفها الثلاثة','📘','لغة عربية','مذكرة شاملة في البلاغة للثانوية العامة بجميع الصفوف، مناسبة للمراجعة والتأسيس.','https://drive.google.com/file/d/1rcocqEmuz8sG9SMgXOfzHeeIgpWVsrHf/view?usp=sharing',20260716,100,FALSE,NULL,FALSE),
(20,'تأسيس إنجلش - العمالقة 2026','🇬🇧','إنجليزي','كتاب تأسيس اللغة الإنجليزية (العمالقة 2026) بصيغة PDF.','https://drive.google.com/file/d/1Vty0yywJ_sPPJ67LFW9ujmtAgZyJ6Ah8/view?usp=sharing',20260716,100,FALSE,NULL,FALSE),
(21,'كورس تأسيس إنجليزي - مستر سعيد الهيت','🇬🇧','إنجليزي','ملف كورس تأسيسي في اللغة الإنجليزية بصيغة PDF.','https://drive.google.com/file/d/1R7LLcvinGsCPZhK_TvKwvnoq_j9M09BM/view?usp=sharing',20260717,100,FALSE,NULL,FALSE),
(22,'الحصة التمهيدية','🎥','برمجة','الحصة التمهيدية.','https://drive.google.com/file/d/1MJRgmiCFnfQU4whC7wDTtW42VcZyYXE9/view?usp=sharing',20260718,100,FALSE,NULL,FALSE),
(23,'ترسيخ العقيدة الإسلامية - 2','📘','مواد شرعية','كتاب ترسيخ العقيدة الإسلامية - 2.','./ترسيخ_العقيدة_الإسلامية-2.html',20260718,100,FALSE,NULL,FALSE),
(24,'قاموس الفكيكه','📖','إنجليزي','قاموس الفكيكه.','./قاموس الفكيكه.html',20260718,100,FALSE,NULL,FALSE),
(25,'كتاب كيان لغة عربية تانية بكالوريا','📖','لغة عربية','كتاب كيان للغة العربية لطلاب تانية بكالوريا.','https://drive.google.com/file/d/1aXVTBXMEb7suoapqTZjHbLnBGPIWyPui/view?usp=sharing',20260929,110,TRUE,NULL,FALSE),
(26,'كتاب العمالقة سنة تانية بكالوريا - الجزء الثاني 2027','🇬🇧','إنجليزي','كتاب العمالقة للصف الثاني الثانوي بكالوريا – الجزء الثاني 2027.','https://drive.google.com/file/d/1mZIXzZD5DaskdzvVEGXrM0DZxCw7WhY3/view?usp=sharing',20260929,110,TRUE,NULL,FALSE),
(27,'الثقافة المالية PDF تانية بكالوريا','💰','ثقافة مالية','ملف الثقافة المالية PDF لطلاب تانية بكالوريا.','https://drive.google.com/file/d/1POmeADij1wPo-5c2FbusKZa3bYibfqPB/view?usp=sharing',20260929,110,TRUE,NULL,FALSE),
(28,'إجابات_المعاصر_تانية_ثانوي_بكالوريا_الترم_الاول_2027','✅','إنجليزي','إجابات المعاصر تانية ثانوي بكالوريا – الترم الأول 2027.','https://drive.google.com/file/d/1VXSqXuikXpknsXYEoQgCY4mIPj3LHjSd/view?usp=sharing',20260929,110,TRUE,NULL,FALSE),
(29,'ملحق_المعاصر_انجليزي_2ث_بكالوريا_الترم_الاول_2027','📎','إنجليزي','ملحق المعاصر إنجليزي 2 ث بكالوريا – الترم الأول 2027.','https://drive.google.com/file/d/1IxXRUpuJ-uzYiycTzFX33Qy8g43eE34I/view?usp=sharing',20260929,110,TRUE,NULL,FALSE),
(30,'كتاب_المعاصر_انجليزي_2بكالوريا_2027_ترم1','📘','إنجليزي','كتاب المعاصر إنجليزي 2 بكالوريا 2027 – الترم الأول.','https://drive.google.com/file/d/1uftB4n53TRWacPzTe7Kmv_HHGLLslZ7q/view?usp=sharing',20260929,110,TRUE,NULL,FALSE),
(31,'كتاب الإنجليزي العمالقة - الجزء الأول','🇬🇧','إنجليزي','كتاب الإنجليزي العمالقة – الجزء الأول.','https://drive.google.com/file/d/1WhYUKpIivmpWmLqf-h1idF2HcjJxlIWQ/view?usp=sharing',20260929,110,TRUE,NULL,FALSE),
(32,'كتاب الأضواء تاريخ تانية بكالوريا','🏛️','تاريخ','كتاب الأضواء لمادة التاريخ لطلاب تانية بكالوريا.','https://drive.google.com/file/d/1_BBe00y41IfyNfPWKYMvol_WqqPsDd_D/view?usp=sharing',20260929,110,TRUE,NULL,FALSE),
(33,'كتاب الامتحان لغة عربية - الجزء الأول 2027','📕','لغة عربية','الجزء الأول من سلسلة كتاب الامتحان في اللغة العربية – 2027.','https://drive.google.com/file/d/14W9FiVD8F1TVMlxlGMwfGqJw5USehBEJ/view?usp=sharing',20260929,110,TRUE,'exam_arabic',FALSE),
(34,'كتاب الامتحان لغة عربية - الجزء الثاني 2027','📕','لغة عربية','الجزء الثاني من سلسلة كتاب الامتحان في اللغة العربية – 2027.','https://drive.google.com/file/d/107Obccz6RVtYLDwiHHYKUm8PwCzjQuh-/view?usp=sharing',20260929,110,TRUE,'exam_arabic',FALSE),
(35,'كتاب الامتحان لغة عربية - الجزء الثالث 2027','📕','لغة عربية','الجزء الثالث من سلسلة كتاب الامتحان في اللغة العربية – 2027.','https://drive.google.com/file/d/1GvsB2L0-S9ZpZaGKwkF_txFOUXy6N78H/view?usp=sharing',20260929,110,TRUE,'exam_arabic',FALSE),
(36,'المواد كاملة 🍒🫂 🤍','📚','المواد كاملة','مجلد Google Drive شامل يحتوي على المواد كاملة.','https://drive.google.com/drive/folders/1mgk5MoazbJ1uUzL3zvvfzltQUOXQoTM2',20260929,120,TRUE,NULL,TRUE),
(37,'العمالقة English-part 3 🩶','🇬🇧','إنجليزي','كتاب العمالقة English-part 3 لطلاب تانية بكالوريا.','https://drive.google.com/file/d/1O0JFW5vkMSa2Xk-bVo0kH4YFLbRGuwVw/view?usp=drivesdk',20260929,130,TRUE,NULL,FALSE),
(38,'محمد صلاح - قاف ثاء 2ث بكالوريا 2027','📘','لغة عربية','كتاب محمد صلاح قاف ثاء لطلاب تانية بكالوريا 2027.','https://drive.google.com/file/d/14RSmYlYUWrc0isvDxRwPiPUT69uyYdU1/view?usp=sharing',20260930,140,TRUE,NULL,FALSE),
(39,'محمد صلاح - طلع الأديب 2ث بكالوريا 2027','📖','لغة عربية','كتاب محمد صلاح طلع الأديب لطلاب تانية بكالوريا 2027.','https://drive.google.com/file/d/1jM6yP51mwDzY_wh2yZJmATyDgbP5Dd8V/view?usp=drivesdk',20260930,140,TRUE,NULL,FALSE),
(40,'محمد صلاح - روائع الأدب 2ث بكالوريا 2027','📚','لغة عربية','كتاب محمد صلاح روائع الأدب لطلاب تانية بكالوريا 2027.','https://drive.google.com/file/d/1JXg9Rt1bam18hNNfBcnLHazK_DMlQ3Lf/view?usp=drivesdk',20260930,140,TRUE,NULL,FALSE),
(41,'محمد صلاح - شرح الجزء الأول 2ث بكالوريا 2027','📕','لغة عربية','شرح الجزء الأول من كتاب محمد صلاح لطلاب تانية بكالوريا 2027.','https://drive.google.com/file/d/1aMLqGD5luF15_fgbA1ZV8wlM0Zujf-nA/view?usp=drivesdk',20260930,140,TRUE,NULL,FALSE),
(42,'محمد صلاح - شرح الجزء الثاني 2ث بكالوريا 2027','📕','لغة عربية','شرح الجزء الثاني من كتاب محمد صلاح لطلاب تانية بكالوريا 2027.','https://drive.google.com/file/d/1MjwFpiFdh2QIoFQabXVpgbilDEOewJuw/view?usp=drivesdk',20260930,140,TRUE,NULL,FALSE),
(43,'شرح البلاغة كاملةً (سلسلة التميز) - 1','📘','لغة عربية','شرح البلاغة كاملةً (سلسلة التميز) - الجزء الأول، برعاية محمد رمضان الحرباوي.','https://drive.google.com/file/d/1qNCxHDF7CDOAkeiGxlMnH204PGE4F5Bo/view?usp=drivesdk',20260930,145,TRUE,NULL,FALSE),
(44,'كتاب ملخص فيزياء تانية بكالوريا','⚡','فيزياء','كتاب ملخص فيزياء تانية بكالوريا، برعاية محمد رمضان الحرباوي.','https://drive.google.com/file/d/1JfC-a11Pc9HzjWJPOc3VBiyD03bCLFLJ/view?usp=sharing',20260930,150,TRUE,NULL,FALSE),
(45,'كتاب الوافي (فيزياء)','⚡','فيزياء','كتاب الوافي في مادة الفيزياء لطلاب تانية بكالوريا.','https://drive.google.com/file/d/1uAjEZbJaGiipdR-cnwo8XCt2H2HaKsVM/view?usp=drivesdk',20260930,150,TRUE,NULL,FALSE),
(46,'كتاب المستر مهاب سلامة - تاريخ وطني تانية بكالوريا','🏛️','تاريخ','كتاب المستر مهاب سلامة في مادة التاريخ الوطني لطلاب تانية بكالوريا، برعاية محمد رمضان الحرباوي.','https://drive.google.com/file/d/17c5i9X5ByrbGk8lHmr94B_zIQSED4ZKT/view?usp=sharing',20260930,0,TRUE,NULL,FALSE),
(47,'كتاب الفائز - برمجه تانيه بكالوريا','💻','برمجة','كتاب الفائز - برمجه تانيه بكالوريا، برعاية محمد رمضان الحرباوي.','https://drive.google.com/file/d/1Qkszte2tWQQ14rHyPgtJEYbQEEVCuaAS/view?usp=sharing',20261001,155,TRUE,NULL,FALSE),
(48,'كتاب الثقافة المالية - تانية بكالوريا 2027','💰','ثقافة مالية','كتاب الثقافة المالية لطلاب تانية بكالوريا 2027.','https://drive.google.com/file/d/12krhB3csGMy3mR7V9il0qm9bntBrzbdc/view?usp=sharing',20261004,160,TRUE,NULL,FALSE),
(49,'طريقة حل أي سؤال فقرة حجاجية','📝','لغة عربية','ملف تدريبي يوضح طريقة حل أي سؤال فقرة حجاجية، للطلاب، برعاية محمد رمضان الحرباوي.','https://drive.google.com/file/d/10FTGkSReUakong6IJJ1CMNHBohdMETUc/view?usp=drivesdk',20261004,165,TRUE,NULL,FALSE),
(50,'بعض التدريبات على الفقرة الحجاجية','✏️','لغة عربية','ملف تدريبات على الفقرة الحجاجية، برعاية محمد رمضان الحرباوي.','https://drive.google.com/file/d/1AmRO8uXtpQsceY_O8tpUSqj-N8v6_IHd/view?usp=drivesdk',20261004,165,TRUE,NULL,FALSE),
(51,'كتاب أ. محمد عبدالمعبود فيزياء - تانية بكالوريا - جزء الشرح','⚡','فيزياء','جزء الشرح من كتاب أ. محمد عبدالمعبود فيزياء لطلاب تانية بكالوريا، برعاية محمد رمضان الحرباوي.','https://drive.google.com/file/d/1ebJ6H2QfJZkpWANKYQu8qEsnlC6RLHcV/view?usp=sharing',20261004,170,TRUE,NULL,FALSE),
(52,'كتاب عبدالمعبود - أسئلة - تانية بكالوريا 2026 - الترم الأول','📝','فيزياء','جزء الأسئلة من كتاب عبدالمعبود فيزياء لطلاب تانية بكالوريا 2026 - الترم الأول، برعاية محمد رمضان الحرباوي.','https://drive.google.com/file/d/1yjCTonMjOL2S_ZyXSCOMAkG4otglNzWG/view?usp=sharing',20261004,170,TRUE,NULL,FALSE),
(53,'كتاب الامتحان تاريخ - تانية بكالوريا','🏛️','تاريخ','كتاب الامتحان في مادة التاريخ لطلاب تانية بكالوريا، برعاية محمد رمضان الحرباوي.','https://drive.google.com/file/d/1RCnANotlh94UtFPWnU0_9ooCcQk_DRid/view?usp=sharing',20261004,175,TRUE,NULL,FALSE)
on conflict (id) do update set
  title=excluded.title, icon=excluded.icon, cat=excluded.cat, description=excluded.description, url=excluded.url, date=excluded.date, popular=excluded.popular, is_new=excluded.is_new, series=excluded.series, is_folder=excluded.is_folder, updated_at=now();

create unique index if not exists ux_notifications_book_title on public.notifications(book_id, title);

-- Seed current library notification items (latest books).
insert into public.notifications (book_id,title,description,category)
select b.id,b.title,b.description,b.cat
from public.books b
where b.id in (51,52,53)
on conflict (book_id,title) do nothing;

-- Optional: after running this file, promote your own user to admin manually:
-- update public.profiles set role='admin' where id='YOUR_AUTH_USER_UUID';
-- Never put the Supabase service_role key in the HTML or client-side code.
